// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	Name        string `gorm:"column:name" json:"name"`
	BeginTime   string `gorm:"column:begin_time" json:"begin_time"`
	EndTime     string `gorm:"column:end_time;not null" json:"end_time"`
	CreatedTime string `gorm:"column:created_time" json:"created_time"`
	UpdatedTime string `gorm:"column:updated_time" json:"updated_time"`
	Skills      string `gorm:"column:skills" json:"skills"`
	Works       string `gorm:"column:works" json:"works"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
