// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

const TableNameToken = "token"

// Token mapped from table <token>
type Token struct {
	ID             int32  `gorm:"column:id" json:"id"`
	UserID         int32  `gorm:"column:user_id" json:"user_id"`
	Key            string `gorm:"column:key" json:"key"`
	Status         int32  `gorm:"column:status" json:"status"`
	Name           string `gorm:"column:name" json:"name"`
	CreateTime     int64  `gorm:"column:create_time" json:"create_time"`
	AccessedTime   int64  `gorm:"column:accessed_time" json:"accessed_time"`
	ExpiredTime    int64  `gorm:"column:expired_time;default:-1" json:"expired_time"`
	RemianQuota    int32  `gorm:"column:remian_quota" json:"remian_quota"`
	UnlimitedQuota bool   `gorm:"column:unlimited_quota" json:"unlimited_quota"`
	UsedQuota      int32  `gorm:"column:used_quota" json:"used_quota"`
}

// TableName Token's table name
func (*Token) TableName() string {
	return TableNameToken
}
