// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID   int32  `gorm:"column:id" json:"id"`
	Name string `gorm:"column:name" json:"name"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
