// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID       int32  `gorm:"column:id" json:"id"`
	Name     string `gorm:"column:name" json:"name"`
	Pwd      string `gorm:"column:pwd" json:"pwd"`
	Token    string `gorm:"column:token" json:"token"`
	Category string `gorm:"column:category" json:"category"`
	Email    string `gorm:"column:email" json:"email"`
	Status   int32  `gorm:"column:status" json:"status"`
	Role     int32  `gorm:"column:role" json:"role"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
