// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package po

const TableNameVlog = "vlogs"

// Vlog mapped from table <vlogs>
type Vlog struct {
	ID          int64  `gorm:"column:id" json:"id"`
	URL         string `gorm:"column:url" json:"url"`
	Desc        string `gorm:"column:desc" json:"desc"`
	CreatedTime string `gorm:"column:created_time" json:"created_time"`
	UpdateTime  string `gorm:"column:update_time" json:"update_time"`
	LikeTimes   int64  `gorm:"column:like_times" json:"like_times"`
}

// TableName Vlog's table name
func (*Vlog) TableName() string {
	return TableNameVlog
}
